# Generated by Django 5.1.7 on 2025-05-08 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiyo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='RecentWork',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
