# Generated by Django 5.1.7 on 2025-05-22 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiyo', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductList',
            new_name='BookList',
        ),
    ]
