# Generated by Django 5.1.7 on 2025-05-22 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiyo', '0005_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
